### PR TITLE
Fix mdc-textfield

### PR DESCRIPTION
**Pull request by djensen47**
Fixes issue #20 

The MDC api for mdc-textfield was updated in v0.22.0, this uses the new API.

### CODE REVIEW

**Comment by djensen47** [comment]
@Ullfis Any chance we can get this pull request merged?

**Comment by Ullfis** [comment]
hmmm.. I only need the code change (your fix commit). Merging had been much easier if you had the fix in a separate branch and created a pull request from that branch. Not sure how I can grab just the fix..

**Comment by djensen47** [comment]
I can roll back the other stuff. The fix was fairly straightforward.

**Comment by Ullfis** [comment]
Looks like I managed to get the fix and add you as Contributor :smile:

Thanks :+1:

**Pull request closed without merging**
